apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: metrics
      port: {{ .Values.configurations.metrics.port }}
      targetPort: {{ .Values.configurations.metrics.port }}
      protocol: TCP
